Repository openshift/tektoncd-pipeline-operator, pull requests merged in 2019-07, with the labels that each got.

#67 Fix CI operator image build
  Makefile
  openshift-ci/Dockerfile.deploy
  openshift-ci/Dockerfile.tools
Labels: size/M

#71 Test pr opo namespace
  make/test.mk
Labels: size/S

#72 Improve Build and Test steps
  make/test.mk
  openshift-ci/Dockerfile.deploy
  openshift-ci/Dockerfile.tools
Labels: size/S

#74 Move installation-status as an enum in config_types
  deploy/crds/operator_v1alpha1_config_crd.yaml
  pkg/apis/operator/v1alpha1/config_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/operator/v1alpha1/zz_generated.openapi.go
  pkg/controller/config/config_controller.go
  test/config/constants.go
  test/testsuites/auto_install_pipeline.go
Labels: lgtm, size/L

#76 Update 0.5.0 csv w.r.t config_types changes
  deploy/olm-catalog/openshift-pipelines-operator/0.5.0/openshift-pipelines-operator.v0.5.0.clusterserviceversion.yaml
  deploy/olm-catalog/openshift-pipelines-operator/0.5.0/operator_v1alpha1_config_crd.yaml
  olm/openshift-pipelines-operator.resources.yaml
Labels: size/M

#78 updates oc and kubectl binaries for CI
  openshift-ci/Dockerfile.tools
Labels: lgtm, size/S

#79 Automatically get latest version when installing oc tools
  openshift-ci/Dockerfile.tools
Labels: lgtm, size/XS

#81 update operator-sdk version to 0.9.0
  openshift-ci/Dockerfile.tools
Labels: size/XS

#82 Add Make targets for generating CSV and operator source
  Makefile
  deploy/install/operator-source.yaml
  make/csv.mk
  make/lint.mk
  manifests/0.5.0/openshift-pipelines-operator.v0.5.0.clusterserviceversion.yaml
  manifests/openshift-pipelines-operator.package.yaml
Labels: size/L

#83 Change operator ns to openshift-operators
  deploy/operator.yaml
  deploy/role_binding.yaml
  deploy/service_account.yaml
  make/test.mk
Labels: lgtm, size/XS
