Repository openshift/tektoncd-pipeline-operator, pull requests merged in 2019-11, with the labels that each got.

#105 OpenShift Pipelines Operator 0.8.0 Release
  deploy/olm-catalog/openshift-pipelines-operator/0.8.0/openshift-pipelines-operator.v0.8.0.clusterserviceversion.yaml
  deploy/olm-catalog/openshift-pipelines-operator/0.8.0/operator_v1alpha1_config_crd.yaml
  deploy/olm-catalog/openshift-pipelines-operator/openshift-pipelines-operator.package.yaml
  deploy/operator.yaml
  deploy/resources/v0.8.0/01-tekton/release.yaml
  deploy/resources/v0.8.0/02-cluster-tasks/echo.yaml
  deploy/resources/v0.8.0/02-cluster-tasks/openshift-client.yaml
  deploy/resources/v0.8.0/03-tasks/openshift-client.yaml
  docs/release.md
  pkg/flag/flag.go
Labels: lgtm, size/XXL

#106 Remove `tasks` directory from 0.8.0 payload
  deploy/resources/v0.8.0/03-tasks/openshift-client.yaml
Labels: lgtm, size/S

#108 Add buildah and s2i tasks
  deploy/resources/v0.8.0/02-cluster-tasks/echo.yaml
  deploy/resources/v0.8.0/02-clustertasks/buildah/buildah-0.8.0-task.yaml
  deploy/resources/v0.8.0/02-clustertasks/buildah/buildah-task.yaml
  deploy/resources/v0.8.0/02-clustertasks/openshift-client/openshift-client-0.8.0-task.yaml
  deploy/resources/v0.8.0/02-clustertasks/openshift-client/openshift-client-task.yaml
  deploy/resources/v0.8.0/02-clustertasks/s2i-go/s2i-go-0.8.0-task.yaml
  deploy/resources/v0.8.0/02-clustertasks/s2i-go/s2i-go-task.yaml
  deploy/resources/v0.8.0/02-clustertasks/s2i-java-11/s2i-java-11-0.8.0-task.yaml
  deploy/resources/v0.8.0/02-clustertasks/s2i-java-11/s2i-java-11-task.yaml
  deploy/resources/v0.8.0/02-clustertasks/s2i-java-8/s2i-java-8-0.8.0-task.yaml
  deploy/resources/v0.8.0/02-clustertasks/s2i-java-8/s2i-java-8-task.yaml
  deploy/resources/v0.8.0/02-clustertasks/s2i-nodejs/s2i-nodejs-0.8.0-task.yaml
  deploy/resources/v0.8.0/02-clustertasks/s2i-nodejs/s2i-nodejs-task.yaml
  deploy/resources/v0.8.0/02-clustertasks/s2i-python-3/s2i-python-3-0.8.0-task.yaml
  deploy/resources/v0.8.0/02-clustertasks/s2i-python-3/s2i-python-3-task.yaml
  deploy/resources/v0.8.0/02-clustertasks/s2i/s2i-0.8.0-task.yaml
  deploy/resources/v0.8.0/02-clustertasks/s2i/s2i-task.yaml
  scripts/update-tasks.sh
Labels: lgtm, size/XXL

#113 Upgrade git, dep and operator-sdk
  openshift-ci/Dockerfile.tools
Labels: size/S

#112 Modify Dockerfile.tools
  openshift-ci/Dockerfile.tools
Labels: lgtm, size/XS

#114 Fix missing dependencies in dockerfile.tools
  openshift-ci/Dockerfile.tools
Labels: size/XS

#109 Fix default tasknames
  deploy/resources/v0.8.0/02-clustertasks/buildah/buildah-v0-8-0-task.yaml
  deploy/resources/v0.8.0/02-clustertasks/openshift-client/openshift-client-v0-8-0-task.yaml
  deploy/resources/v0.8.0/02-clustertasks/s2i-go/s2i-go-v0-8-0-task.yaml
  deploy/resources/v0.8.0/02-clustertasks/s2i-java-11/s2i-java-11-v0-8-0-task.yaml
  deploy/resources/v0.8.0/02-clustertasks/s2i-java-8/s2i-java-8-v0-8-0-task.yaml
  deploy/resources/v0.8.0/02-clustertasks/s2i-nodejs/s2i-nodejs-v0-8-0-task.yaml
  deploy/resources/v0.8.0/02-clustertasks/s2i-python-3/s2i-python-3-v0-8-0-task.yaml
  deploy/resources/v0.8.0/02-clustertasks/s2i/s2i-v0-8-0-task.yaml
  scripts/update-tasks.sh
Labels: size/S

#107 Add Triggers Release
  deploy/resources/v0.8.0/03-triggers/tektoncd-triggers-v0.1.0.yaml
Labels: size/XL

#110 Adds Trigger E2E tests
  pkg/flag/flag.go
  test/testsuites/auto_install_pipeline.go
Labels: lgtm, size/S

#115 Fix typo in ClusterTask workingdir -> workingDir
  deploy/resources/v0.8.0/02-clustertasks/s2i-go/s2i-go-task.yaml
  deploy/resources/v0.8.0/02-clustertasks/s2i-go/s2i-go-v0-8-0-task.yaml
  deploy/resources/v0.8.0/02-clustertasks/s2i-java-11/s2i-java-11-task.yaml
  deploy/resources/v0.8.0/02-clustertasks/s2i-java-11/s2i-java-11-v0-8-0-task.yaml
  deploy/resources/v0.8.0/02-clustertasks/s2i-java-8/s2i-java-8-task.yaml
  deploy/resources/v0.8.0/02-clustertasks/s2i-java-8/s2i-java-8-v0-8-0-task.yaml
  deploy/resources/v0.8.0/02-clustertasks/s2i-nodejs/s2i-nodejs-task.yaml
  deploy/resources/v0.8.0/02-clustertasks/s2i-nodejs/s2i-nodejs-v0-8-0-task.yaml
  deploy/resources/v0.8.0/02-clustertasks/s2i-python-3/s2i-python-3-task.yaml
  deploy/resources/v0.8.0/02-clustertasks/s2i-python-3/s2i-python-3-v0-8-0-task.yaml
  deploy/resources/v0.8.0/02-clustertasks/s2i/s2i-task.yaml
  deploy/resources/v0.8.0/02-clustertasks/s2i/s2i-v0-8-0-task.yaml
  scripts/update-tasks.sh
Labels: lgtm, size/M

#117 Update README.md
  README.md
Labels: lgtm, size/XS

#116 Adds OWNERS for CI auto merge to work
  OWNERS
Labels: lgtm, size/XS

#120 Ensure clustertasks are viewable by authenticated users
  deploy/resources/v0.8.0/02-clustertasks/cluster-role.yaml
  deploy/resources/v0.8.0/02-clustertasks/cluster-rolebinding.yaml
Labels: approved, lgtm, size/S

#119 Add mechanism to sync release-next branch
  openshift/release/update-to-head.sh
Labels: approved, lgtm, size/S

#121 Ensure clusterTasks have default values set
  deploy/resources/v0.8.0/02-clustertasks/buildah/buildah-task.yaml
  deploy/resources/v0.8.0/02-clustertasks/buildah/buildah-v0-8-0-task.yaml
  deploy/resources/v0.8.0/02-clustertasks/openshift-client/openshift-client-task.yaml
  deploy/resources/v0.8.0/02-clustertasks/openshift-client/openshift-client-v0-8-0-task.yaml
  deploy/resources/v0.8.0/02-clustertasks/s2i-go/s2i-go-task.yaml
  deploy/resources/v0.8.0/02-clustertasks/s2i-go/s2i-go-v0-8-0-task.yaml
  deploy/resources/v0.8.0/02-clustertasks/s2i-java-11/s2i-java-11-task.yaml
  deploy/resources/v0.8.0/02-clustertasks/s2i-java-11/s2i-java-11-v0-8-0-task.yaml
  deploy/resources/v0.8.0/02-clustertasks/s2i-java-8/s2i-java-8-task.yaml
  deploy/resources/v0.8.0/02-clustertasks/s2i-java-8/s2i-java-8-v0-8-0-task.yaml
  deploy/resources/v0.8.0/02-clustertasks/s2i-nodejs/s2i-nodejs-task.yaml
  deploy/resources/v0.8.0/02-clustertasks/s2i-nodejs/s2i-nodejs-v0-8-0-task.yaml
  deploy/resources/v0.8.0/02-clustertasks/s2i-python-3/s2i-python-3-task.yaml
  deploy/resources/v0.8.0/02-clustertasks/s2i-python-3/s2i-python-3-v0-8-0-task.yaml
  deploy/resources/v0.8.0/02-clustertasks/s2i/s2i-task.yaml
  deploy/resources/v0.8.0/02-clustertasks/s2i/s2i-v0-8-0-task.yaml
Labels: approved, lgtm, size/XXL
