Repository openshift/tektoncd-pipeline-operator, pull requests merged in 2019-06, with the labels that each got.

#19 Improve test structure and adds additional tests
  docs/tests.md
  test/config/constants.go
  test/e2e/main_test.go
  test/e2e/openshift-pipelines-operator_test.go
  test/helpers/helpers.go
  test/testgroups/installcrdtest.go
  test/testsuites/installcrdcreatetests.go
  test/testsuites/installcrddeletetests.go
Labels: lgtm, size/L

#21 Add operator-ci to execute integration tests for PRs, nightly, and releases
  .yamllint
  Makefile
  deploy/crds/openshift_v1alpha1_install_crd.yaml
  make/dev.mk
  make/docker.mk
  make/find-tools.mk
  make/format.mk
  make/git.mk
  make/go.mk
  make/help.mk
  make/lint.mk
  make/out.mk
  make/test.mk
  make/verbose.mk
  openshift-ci/Dockerfile.deploy
  openshift-ci/Dockerfile.registry.build
  openshift-ci/Dockerfile.registry.build.next
  openshift-ci/Dockerfile.registry.intermediate
  openshift-ci/Dockerfile.tools
  openshift-ci/Dockerfile.upgrade.build
  openshift-ci/README.md
Labels: ok-to-test, size/XL

#25 Fix Makefiles and linting errors
  .gitignore
  deploy/olm-catalog/openshift-pipelines-operator/0.3.1/openshift-pipelines-operator.v0.3.1.clusterserviceversion.yaml
  deploy/resources/v0.3.1/release.yaml
  gofmt_exclude
  make/dev.mk
  olm/openshift-pipelines-operator.resources.yaml
  pkg/controller/install/install_controller.go
  scripts/olm_catalog.sh
Labels: size/M

#27 Disable courier yaml target
  make/lint.mk
Labels: size/XS

#29 Fix CI build
  Makefile
Labels: lgtm, size/XS

#33 Update tests.md with correct numbering
  docs/tests.md
Labels: ok-to-test, size/XS

#32 Correct the name of cr
  deploy/crds/openshift_v1alpha1_install_cr.yaml
Labels: lgtm, needs-ok-to-test, size/XS

#37 Update Dockerfiles and filepaths for CI
  deploy/olm-catalog/openshift-pipelines-operator/0.3.1/openshift-pipelines-operator-tekton_v1alpha1_install_crd.yaml
  deploy/olm-catalog/openshift-pipelines-operator/0.3.1/openshift-pipelines-operator.v0.3.1.clusterserviceversion.yaml
  openshift-ci/Dockerfile.registry.build
Labels: size/M

#45 Add a hack to make sure CI builds images
  Makefile
  openshift-ci/Dockerfile.registry.build
Labels: size/S

#22 Upgrades wrt openshift-pipelines v0.4.0 release
  deploy/olm-catalog/openshift-pipelines-operator/0.4.0/openshift-pipelines-operator-tekton_v1alpha1_install_crd.yaml
  deploy/olm-catalog/openshift-pipelines-operator/0.4.0/openshift-pipelines-operator.v0.4.0.clusterserviceversion.yaml
  deploy/olm-catalog/openshift-pipelines-operator/openshift-pipelines-operator.package.yaml
  deploy/operator.yaml
  deploy/resources/v0.4.0/release.yaml
  deploy/role.yaml
  olm/openshift-pipelines-operator.resources.yaml
  openshift-ci/Dockerfile.registry.build
  pkg/controller/install/install_controller.go
  scripts/olm_catalog.sh
Labels: lgtm, size/XXL

#35 Changed the container runtime references
  README.md
Labels: size/XS

#50 Set e2e test timeout to 30m
  make/test.mk
Labels: size/XS

#52 Fixes typos in CSV description
  deploy/olm-catalog/openshift-pipelines-operator/0.3.1/openshift-pipelines-operator.v0.3.1.clusterserviceversion.yaml
  deploy/olm-catalog/openshift-pipelines-operator/0.4.0/openshift-pipelines-operator.v0.4.0.clusterserviceversion.yaml
Labels: size/XS

#60 Update operator-sdk version to 0.8.1 in build_root
  openshift-ci/Dockerfile.tools
Labels: size/XS
