Repository openshift/tektoncd-pipeline-operator, pull requests merged in 2019-04, with the labels that each got.

#2 Refactor olm parts
  olm/tektoncd-pipeline-operator.resources.yaml
  scripts/olm_catalog.sh
Labels: size/S

#4 Update image tags
  deploy/olm-catalog/csv-config.yaml
  deploy/olm-catalog/tektoncd-pipeline-operator/0.0.1/tektoncd-pipeline-operator.v0.0.1.clusterserviceversion.yaml
  deploy/operator.yaml
  deploy/resources/release-0.0.1.yaml
  olm/tektoncd-pipeline-operator.resources.yaml
  pkg/controller/install/install_controller.go
Labels: size/L

#5 updates based on operator-sdk scorecard test
  .osdk-scorecard.yaml
  deploy/crds/tekton_v1alpha1_install_cr.yaml
  deploy/olm-catalog/tektoncd-pipeline-operator/0.0.1/tektoncd-pipeline-operator.v0.0.1.clusterserviceversion.yaml
  olm/tektoncd-pipeline-operator.resources.yaml
Labels: size/M

#7 Update operator wrt tektoncd-pipeline release v0.3.1
  build/Dockerfile
  deploy/olm-catalog/tektoncd-pipeline-operator/0.3.1/tektoncd-pipeline-operator.v0.3.1.clusterserviceversion.yaml
  deploy/olm-catalog/tektoncd-pipeline-operator/tektoncd-pipeline-operator.package.yaml
  deploy/olm-catalog/tektoncd-pipeline-operator/tektoncd.package.yaml
  deploy/operator.yaml
  deploy/resources/v0.3.1/release.yaml
  deploy/role.yaml
  olm/tektoncd-pipeline-operator.resources.yaml
  pkg/controller/install/install_controller.go
  scripts/olm_catalog.sh
Labels: lgtm, size/L
