Repository openshift/tektoncd-pipeline-operator, pull requests merged in 2019-12, with the labels that each got.

#124 Fix webhook timing issue while installing clustertasks and triggers
  deploy/resources/v0.8.0/02-clustertasks/buildah/buildah-task.yaml
  deploy/resources/v0.8.0/02-clustertasks/buildah/buildah-v0-8-0-task.yaml
  deploy/resources/v0.8.0/02-clustertasks/openshift-client/openshift-client-task.yaml
  deploy/resources/v0.8.0/02-clustertasks/openshift-client/openshift-client-v0-8-0-task.yaml
  deploy/resources/v0.8.0/02-clustertasks/s2i-go/s2i-go-v0-8-0-task.yaml
  deploy/resources/v0.8.0/02-clustertasks/s2i-java-11/s2i-java-11-task.yaml
  deploy/resources/v0.8.0/02-clustertasks/s2i-java-11/s2i-java-11-v0-8-0-task.yaml
  deploy/resources/v0.8.0/02-clustertasks/s2i-java-8/s2i-java-8-task.yaml
  deploy/resources/v0.8.0/02-clustertasks/s2i-java-8/s2i-java-8-v0-8-0-task.yaml
  deploy/resources/v0.8.0/02-clustertasks/s2i-nodejs/s2i-nodejs-v0-8-0-task.yaml
  deploy/resources/v0.8.0/02-clustertasks/s2i-python-3/s2i-python-3-task.yaml
  deploy/resources/v0.8.0/02-clustertasks/s2i-python-3/s2i-python-3-v0-8-0-task.yaml
  deploy/resources/v0.8.0/02-clustertasks/s2i/s2i-task.yaml
  deploy/resources/v0.8.0/02-clustertasks/s2i/s2i-v0-8-0-task.yaml
  deploy/resources/v0.8.0/addons/clustertasks/buildah/buildah-task.yaml
  deploy/resources/v0.8.0/addons/clustertasks/buildah/buildah-v0-8-0-task.yaml
  deploy/resources/v0.8.0/addons/clustertasks/cluster-role.yaml
  deploy/resources/v0.8.0/addons/clustertasks/cluster-rolebinding.yaml
  deploy/resources/v0.8.0/addons/clustertasks/openshift-client/openshift-client-task.yaml
  deploy/resources/v0.8.0/addons/clustertasks/openshift-client/openshift-client-v0-8-0-task.yaml
  deploy/resources/v0.8.0/addons/clustertasks/s2i-go/s2i-go-task.yaml
  deploy/resources/v0.8.0/addons/clustertasks/s2i-go/s2i-go-v0-8-0-task.yaml
  deploy/resources/v0.8.0/addons/clustertasks/s2i-java-11/s2i-java-11-task.yaml
  deploy/resources/v0.8.0/addons/clustertasks/s2i-java-11/s2i-java-11-v0-8-0-task.yaml
  deploy/resources/v0.8.0/addons/clustertasks/s2i-java-8/s2i-java-8-task.yaml
  deploy/resources/v0.8.0/addons/clustertasks/s2i-java-8/s2i-java-8-v0-8-0-task.yaml
  deploy/resources/v0.8.0/addons/clustertasks/s2i-nodejs/s2i-nodejs-task.yaml
  deploy/resources/v0.8.0/addons/clustertasks/s2i-nodejs/s2i-nodejs-v0-8-0-task.yaml
  deploy/resources/v0.8.0/addons/clustertasks/s2i-python-3/s2i-python-3-task.yaml
  deploy/resources/v0.8.0/addons/clustertasks/s2i-python-3/s2i-python-3-v0-8-0-task.yaml
  deploy/resources/v0.8.0/addons/clustertasks/s2i/s2i-task.yaml
  deploy/resources/v0.8.0/addons/clustertasks/s2i/s2i-v0-8-0-task.yaml
  deploy/resources/v0.8.0/addons/triggers/tektoncd-triggers-v0.1.0.yaml
  deploy/resources/v0.8.0/pipelines/release.yaml
  pkg/apis/operator/v1alpha1/config_types.go
  pkg/controller/config/config_controller.go
  pkg/controller/validate/validate.go
  scripts/update-tasks.sh
Labels: approved, lgtm, size/XXL

#132 :robot: Triggering CI on branch 'release-next' after synching to openshift/master
  ci
Labels: kind/sync-fork-to-upstream, size/XS

#134 Fix operator uuid not propogating to controller
  build/bin/entrypoint
  pkg/flag/flag.go
Labels: approved, lgtm, size/S

#136 Update operator CSV chaining
  deploy/olm-catalog/openshift-pipelines-operator/0.8.1/openshift-pipelines-operator.v0.8.1.clusterserviceversion.yaml
  deploy/olm-catalog/openshift-pipelines-operator/openshift-pipelines-operator.package.yaml
Labels: approved, lgtm, size/XS

#140 Add annotation to CSV to hide internal CRD's
  deploy/olm-catalog/openshift-pipelines-operator/0.9.0/openshift-pipelines-operator.v0.9.0.clusterserviceversion.yaml
  deploy/olm-catalog/openshift-pipelines-operator/0.9.0/operator_v1alpha1_config_crd.yaml
Labels: approved, lgtm, size/L

#142 Bump operator sdk to 0.10.1 😅
  go.mod
  go.sum
  vendor/github.com/operator-framework/operator-sdk/internal/pkg/scaffold/cmd.go
  vendor/github.com/operator-framework/operator-sdk/internal/pkg/scaffold/go_mod.go
  vendor/github.com/operator-framework/operator-sdk/internal/pkg/scaffold/gopkgtoml.go
  vendor/github.com/operator-framework/operator-sdk/internal/pkg/scaffold/role.go
  vendor/github.com/operator-framework/operator-sdk/internal/pkg/scaffold/test_setup.go
  vendor/github.com/operator-framework/operator-sdk/internal/util/k8sutil/k8sutil.go
  vendor/github.com/operator-framework/operator-sdk/pkg/k8sutil/k8sutil.go
  vendor/github.com/operator-framework/operator-sdk/pkg/leader/leader.go
  vendor/github.com/operator-framework/operator-sdk/pkg/log/zap/flags.go
  vendor/github.com/operator-framework/operator-sdk/pkg/log/zap/logger.go
  vendor/github.com/operator-framework/operator-sdk/pkg/metrics/metrics.go
  vendor/github.com/operator-framework/operator-sdk/pkg/metrics/service-monitor.go
  vendor/github.com/operator-framework/operator-sdk/version/version.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#143 Validate the webhooks are registered
  pkg/apis/operator/v1alpha1/config_types.go
  pkg/controller/config/config_controller.go
  pkg/flag/flag.go
  pkg/utils/transform/transform.go
  pkg/utils/validate/validate.go
Labels: approved, lgtm, size/L

#125 Add pipeline samples for UI
  deploy/resources/v0.8.0/optional/pipelinesamples/docker_build_deploy.yaml
  deploy/resources/v0.8.0/optional/pipelinesamples/s2i_build_deploy.yaml
  deploy/resources/v0.8.0/optional/pipelinesamples/simple_pipeline.yaml
  go.mod
  pkg/controller/config/config_controller.go
  pkg/utils/validate/validate.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/clientset.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/apiextensions_client.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/generated_expansion.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#155 Updates make build target for productization
  Makefile
Labels: approved, lgtm, size/S

#127 Add task snippets for YAML editor
  deploy/resources/v0.8.0/optional/tasksnippets/buildah-task-snippet.yaml
  deploy/resources/v0.8.0/optional/tasksnippets/openshift-client-task-snippet.yaml
  deploy/resources/v0.8.0/optional/tasksnippets/s2i-go-task-snippet.yaml
  deploy/resources/v0.8.0/optional/tasksnippets/s2i-java-11-task-snippet.yaml
  deploy/resources/v0.8.0/optional/tasksnippets/s2i-java-8-task-snippet.yaml
  deploy/resources/v0.8.0/optional/tasksnippets/s2i-nodejs-task-snippet.yaml
  deploy/resources/v0.8.0/optional/tasksnippets/s2i-python-3-task-snippet.yaml
  deploy/resources/v0.8.0/optional/tasksnippets/s2i-task-snippet.yaml
Labels: approved, lgtm, ok-to-test, size/L

#156 Release-v0.9.0
  Makefile
  deploy/olm-catalog/openshift-pipelines-operator/0.9.0/openshift-pipelines-operator.v0.9.0.clusterserviceversion.yaml
  deploy/olm-catalog/openshift-pipelines-operator/openshift-pipelines-operator.package.yaml
  deploy/operator.yaml
  deploy/resources/v0.9.2/addons/clustertasks/buildah/buildah-task.yaml
  deploy/resources/v0.9.2/addons/clustertasks/buildah/buildah-v0-8-0-task.yaml
  deploy/resources/v0.9.2/addons/clustertasks/cluster-role.yaml
  deploy/resources/v0.9.2/addons/clustertasks/cluster-rolebinding.yaml
  deploy/resources/v0.9.2/addons/clustertasks/openshift-client/openshift-client-task.yaml
  deploy/resources/v0.9.2/addons/clustertasks/openshift-client/openshift-client-v0-8-0-task.yaml
  deploy/resources/v0.9.2/addons/clustertasks/s2i-go/s2i-go-task.yaml
  deploy/resources/v0.9.2/addons/clustertasks/s2i-go/s2i-go-v0-8-0-task.yaml
  deploy/resources/v0.9.2/addons/clustertasks/s2i-java-11/s2i-java-11-task.yaml
  deploy/resources/v0.9.2/addons/clustertasks/s2i-java-11/s2i-java-11-v0-8-0-task.yaml
  deploy/resources/v0.9.2/addons/clustertasks/s2i-java-8/s2i-java-8-task.yaml
  deploy/resources/v0.9.2/addons/clustertasks/s2i-java-8/s2i-java-8-v0-8-0-task.yaml
  deploy/resources/v0.9.2/addons/clustertasks/s2i-nodejs/s2i-nodejs-task.yaml
  deploy/resources/v0.9.2/addons/clustertasks/s2i-nodejs/s2i-nodejs-v0-8-0-task.yaml
  deploy/resources/v0.9.2/addons/clustertasks/s2i-python-3/s2i-python-3-task.yaml
  deploy/resources/v0.9.2/addons/clustertasks/s2i-python-3/s2i-python-3-v0-8-0-task.yaml
  deploy/resources/v0.9.2/addons/clustertasks/s2i/s2i-task.yaml
  deploy/resources/v0.9.2/addons/clustertasks/s2i/s2i-v0-8-0-task.yaml
  deploy/resources/v0.9.2/addons/triggers/tektoncd-triggers-v0.1.0.yaml
  deploy/resources/v0.9.2/optional/pipelinesamples/docker_build_deploy.yaml
  deploy/resources/v0.9.2/optional/pipelinesamples/s2i_build_deploy.yaml
  deploy/resources/v0.9.2/optional/pipelinesamples/simple_pipeline.yaml
  deploy/resources/v0.9.2/optional/tasksnippets/buildah-task-snippet.yaml
  deploy/resources/v0.9.2/optional/tasksnippets/openshift-client-task-snippet.yaml
  deploy/resources/v0.9.2/optional/tasksnippets/s2i-go-task-snippet.yaml
  deploy/resources/v0.9.2/optional/tasksnippets/s2i-java-11-task-snippet.yaml
  deploy/resources/v0.9.2/optional/tasksnippets/s2i-java-8-task-snippet.yaml
  deploy/resources/v0.9.2/optional/tasksnippets/s2i-nodejs-task-snippet.yaml
  deploy/resources/v0.9.2/optional/tasksnippets/s2i-python-3-task-snippet.yaml
  deploy/resources/v0.9.2/optional/tasksnippets/s2i-task-snippet.yaml
  deploy/resources/v0.9.2/pipelines/release.yaml
  deploy/role.yaml
  docs/release.md
  pkg/flag/flag.go
Labels: approved, lgtm, size/XXL

#138 Add mechanism to fetch nightly/latest pipeline payload
  openshift/release/fetch-pipeline.sh
  openshift/release/update-to-head.sh
Labels: approved, lgtm, size/M

#164 Add mechanism to update TektonVersion flag for nightly
  openshift/release/fetch-pipeline.sh
  openshift/release/update-to-head.sh
Labels: approved, lgtm, size/XS
