Repository openshift/tektoncd-pipeline-operator, pull requests merged in 2019-10, with the labels that each got.

#95 Fix CI by upgrading to operator-sdk version
  go.mod
  go.sum
  make/lint.mk
  vendor/github.com/google/btree/btree_mem.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/golang.org/x/text/width/gen.go
  vendor/golang.org/x/text/width/gen_common.go
  vendor/golang.org/x/text/width/gen_trieval.go
  vendor/golang.org/x/tools/go/gcexportdata/main.go
  vendor/golang.org/x/tools/imports/mkindex.go
  vendor/golang.org/x/tools/imports/mkstdlib.go
  vendor/modules.txt
Labels: lgtm, size/XXL

#93 Update readme to reflect how to override the created docker tag
  README.md
Labels: ok-to-test, size/XS

#97 update readme based on changes in #83
  README.md
Labels: lgtm, ok-to-test, size/S

#92 Auto creates SA and RBAC for pipelines
  Makefile
  deploy/resources/v0.7.0/release.yaml
  deploy/role.yaml
  go.mod
  go.sum
  make/test.mk
  pkg/apis/operator/v1alpha1/zz_generated.openapi.go
  pkg/controller/add_rbac.go
  pkg/controller/config/config_controller.go
  pkg/controller/rbac/rbac_controller.go
  test/helpers/helpers.go
  test/testgroups/cluster_crd.go
  test/testsuites/auto_default_sa.go
  test/testsuites/auto_install_pipeline.go
  vendor/github.com/openshift/api/LICENSE
  vendor/github.com/openshift/api/security/v1/consts.go
  vendor/github.com/openshift/api/security/v1/doc.go
  vendor/github.com/openshift/api/security/v1/generated.pb.go
  vendor/github.com/openshift/api/security/v1/generated.proto
  vendor/github.com/openshift/api/security/v1/legacy.go
  vendor/github.com/openshift/api/security/v1/register.go
  vendor/github.com/openshift/api/security/v1/types.go
  vendor/github.com/openshift/api/security/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/security/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/client-go/LICENSE
  vendor/github.com/openshift/client-go/security/clientset/versioned/scheme/doc.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/scheme/register.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/doc.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/generated_expansion.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/podsecuritypolicyreview.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/podsecuritypolicyselfsubjectreview.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/podsecuritypolicysubjectreview.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/rangeallocation.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/security_client.go
  vendor/github.com/openshift/client-go/security/clientset/versioned/typed/security/v1/securitycontextconstraints.go
  vendor/modules.txt
Labels: size/XXL

#98 Update readme to reflect the needed change in catalog namespace
  README.md
Labels: lgtm, ok-to-test, size/XS

#100 Release 0.7
  deploy/olm-catalog/openshift-pipelines-operator/0.7.0/openshift-pipelines-operator.v0.7.0.clusterserviceversion.yaml
  deploy/olm-catalog/openshift-pipelines-operator/0.7.0/operator_v1alpha1_config_crd.yaml
  deploy/olm-catalog/openshift-pipelines-operator/openshift-pipelines-operator.package.yaml
  deploy/operator.yaml
  deploy/resources/v0.7.0/release.yaml
  deploy/role.yaml
  docs/release.md
  olm/operator-source.yaml
  olm/subscription.yaml
  pkg/controller/rbac/rbac_controller.go
Labels: size/XXL

#101 Add inject-Default-SA Transformer
  cmd/manager/main.go
  pkg/controller/config/config_controller.go
  pkg/controller/rbac/rbac_controller.go
  pkg/controller/transform/transform.go
  pkg/flag/flag.go
  test/testsuites/auto_default_sa.go
  test/testsuites/auto_install_pipeline.go
Labels: lgtm, size/L

#103 Update yamllint rules
  .yamllint
Labels: lgtm, size/XS
