Repository openshift/tektoncd-pipeline-operator, pull requests merged in 2019-05, with the labels that each got.

#8 Update README.md
  README.md
Labels: size/XS

#6 updates based on pr to community operators
  .osdk-scorecard.yaml
  build/Dockerfile
  deploy/crds/openshift-pipelines-operator-tekton_v1alpha1_install_crd.yaml
  deploy/crds/openshift_v1alpha1_install_cr.yaml
  deploy/olm-catalog/openshift-pipelines-operator/0.3.1/openshift-pipelines-operator.v0.3.1.clusterserviceversion.yaml
  deploy/olm-catalog/openshift-pipelines-operator/openshift-pipelines-operator.package.yaml
  deploy/olm-catalog/tektoncd-pipeline-operator/tektoncd-pipeline-operator.package.yaml
  deploy/operator-group.yaml
  deploy/operator.yaml
  deploy/resources/v0.3.1/release.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  deploy/service_account.yaml
  olm/openshift-pipelines-operator.resources.yaml
  pkg/controller/install/install_controller.go
  scripts/olm_catalog.sh
Labels: size/XL

#9 Add E2E tests
  Gopkg.lock
  deploy/namespace.yaml
  deploy/operator-group.yaml
  deploy/operator.yaml
  deploy/role_binding.yaml
  deploy/service_account.yaml
  docs/tests.md
  test/e2e/main_test.go
  test/e2e/openshift-pipelines-operator_test.go
  vendor/github.com/BurntSushi/toml/COPYING
  vendor/github.com/BurntSushi/toml/_examples/example.go
  vendor/github.com/BurntSushi/toml/cmd/toml-test-decoder/COPYING
  vendor/github.com/BurntSushi/toml/cmd/toml-test-decoder/main.go
  vendor/github.com/BurntSushi/toml/cmd/toml-test-encoder/COPYING
  vendor/github.com/BurntSushi/toml/cmd/toml-test-encoder/main.go
  vendor/github.com/BurntSushi/toml/cmd/tomlv/COPYING
  vendor/github.com/BurntSushi/toml/cmd/tomlv/main.go
  vendor/github.com/BurntSushi/toml/decode.go
  vendor/github.com/BurntSushi/toml/decode_meta.go
  vendor/github.com/BurntSushi/toml/doc.go
  vendor/github.com/BurntSushi/toml/encode.go
  vendor/github.com/BurntSushi/toml/encoding_types.go
  vendor/github.com/BurntSushi/toml/encoding_types_1.1.go
  vendor/github.com/BurntSushi/toml/lex.go
  vendor/github.com/BurntSushi/toml/parse.go
  vendor/github.com/BurntSushi/toml/type_check.go
  vendor/github.com/BurntSushi/toml/type_fields.go
  vendor/github.com/konsorten/go-windows-terminal-sequences/LICENSE
  vendor/github.com/konsorten/go-windows-terminal-sequences/sequences.go
  vendor/github.com/konsorten/go-windows-terminal-sequences/sequences_dummy.go
  vendor/github.com/sirupsen/logrus/LICENSE
  vendor/github.com/sirupsen/logrus/alt_exit.go
  vendor/github.com/sirupsen/logrus/doc.go
  vendor/github.com/sirupsen/logrus/entry.go
  vendor/github.com/sirupsen/logrus/exported.go
  vendor/github.com/sirupsen/logrus/formatter.go
  vendor/github.com/sirupsen/logrus/hooks.go
  vendor/github.com/sirupsen/logrus/hooks/syslog/syslog.go
  vendor/github.com/sirupsen/logrus/hooks/test/test.go
  vendor/github.com/sirupsen/logrus/internal/testutils/testutils.go
  vendor/github.com/sirupsen/logrus/json_formatter.go
  vendor/github.com/sirupsen/logrus/logger.go
  vendor/github.com/sirupsen/logrus/logrus.go
  vendor/github.com/sirupsen/logrus/terminal_check_appengine.go
  vendor/github.com/sirupsen/logrus/terminal_check_bsd.go
  vendor/github.com/sirupsen/logrus/terminal_check_js.go
  vendor/github.com/sirupsen/logrus/terminal_check_notappengine.go
  vendor/github.com/sirupsen/logrus/terminal_check_unix.go
  vendor/github.com/sirupsen/logrus/terminal_check_windows.go
  vendor/github.com/sirupsen/logrus/terminal_notwindows.go
  vendor/github.com/sirupsen/logrus/terminal_windows.go
  vendor/github.com/sirupsen/logrus/text_formatter.go
  vendor/github.com/sirupsen/logrus/writer.go
Labels: lgtm, ok-to-test, size/XXL

#11 Updated operator description and icon
  deploy/olm-catalog/openshift-pipelines-operator/0.3.1/openshift-pipelines-operator.v0.3.1.clusterserviceversion.yaml
  olm/openshift-pipelines-operator.resources.yaml
Labels: lgtm, size/M

#10 README update
  README.md
Labels: size/M

#12 Fix development install issues
  README.md
  deploy/crds/openshift_v1alpha1_install_cr.yaml
Labels: lgtm, size/XS

#13 Update README.md
  README.md
Labels: size/L

#15 remove duplicate step
  README.md
Labels: size/XS

#16 Use latest manifestival pkg
  Gopkg.lock
  Gopkg.toml
  deploy/operator.yaml
  pkg/controller/install/install_controller.go
  vendor/github.com/jcrossley3/manifestival/manifestival.go
  vendor/github.com/jcrossley3/manifestival/transform.go
  vendor/github.com/jcrossley3/manifestival/yaml.go
Labels: lgtm, size/L

#17 Use deleteOption DeletePropagationForeground while deleting resources
  Gopkg.lock
  Gopkg.toml
  deploy/operator.yaml
  pkg/controller/install/install_controller.go
  test/e2e/openshift-pipelines-operator_test.go
  vendor/github.com/jcrossley3/manifestival/manifestival.go
  vendor/github.com/jcrossley3/manifestival/transform.go
  vendor/github.com/jcrossley3/manifestival/yaml.go
Labels: lgtm, size/L

#18 Install Openshift-Pipelines into Opreator Namespace
  .osdk-scorecard.yaml
  deploy/olm-catalog/openshift-pipelines-operator/0.3.1/openshift-pipelines-operator.v0.3.1.clusterserviceversion.yaml
  deploy/operator.yaml
  deploy/resources/v0.3.1/release.yaml
  olm/openshift-pipelines-operator.resources.yaml
  pkg/controller/install/install_controller.go
  test/e2e/openshift-pipelines-operator_test.go
Labels: lgtm, size/M
