Repository openshift/tektoncd-pipeline-operator, pull requests merged in 2020-10, with the labels that each got.

#468 Refactor in clustertask provided type
  bundle/manifests/openshift-pipelines-operator.clusterserviceversion.yaml
  deploy/operator.yaml
  deploy/resources/addons/02-clustertasks/kn/kn-task.yaml
  deploy/resources/addons/02-clustertasks/kn/kn-v0-16-3-task.yaml
  pkg/controller/config/config_controller.go
  pkg/flag/flag.go
  scripts/update-tasks.sh
Labels: approved, lgtm

#469 Add v1.2 Changes to flag pkg
  bundle.Dockerfile
  bundle/metadata/annotations.yaml
  pkg/flag/flag.go
Labels: approved, lgtm

#471 Move skopeo-copy task to Red Hat Type
  deploy/operator.yaml
  deploy/resources/addons/02-clustertasks/skopeo-copy/skopeo-copy-task.yaml
  deploy/resources/addons/02-clustertasks/skopeo-copy/skopeo-copy-v0-16-3-task.yaml
  pkg/flag/flag.go
  scripts/update-tasks.sh
Labels: approved, lgtm

#472 Move skopeo-copy task to Red Hat Type
  deploy/operator.yaml
  deploy/resources/addons/02-clustertasks/skopeo-copy/skopeo-copy-task.yaml
  deploy/resources/addons/02-clustertasks/skopeo-copy/skopeo-copy-v0-16-3-task.yaml
  pkg/flag/flag.go
  scripts/update-tasks.sh
Labels: approved, lgtm

#482 Add Aggregate View for Trigger CRD
  deploy/resources/triggers/rolebindingedit.yaml
  deploy/resources/triggers/rolebindingview.yaml
Labels: approved, lgtm

#486 :robot: Triggering CI on branch 'release-next' after synching to openshift/master
  ci
Labels: kind/sync-fork-to-upstream

#490 Update images tag to digest
  scripts/update-tasks.sh
Labels: approved, lgtm

#488 skip installation of tektoncd/catalog tasks if the platform is not x8…
  pkg/controller/config/config_controller.go
Labels: approved, lgtm, ok-to-test

#493 Run script to update all cluster task to use digest
  deploy/resources/addons/02-clustertasks/buildah-pr/buildah-pr-task.yaml
  deploy/resources/addons/02-clustertasks/buildah-pr/buildah-pr-v0-16-3-task.yaml
  deploy/resources/addons/02-clustertasks/buildah/buildah-task.yaml
  deploy/resources/addons/02-clustertasks/buildah/buildah-v0-16-3-task.yaml
  deploy/resources/addons/02-clustertasks/kn/kn-task.yaml
  deploy/resources/addons/02-clustertasks/kn/kn-v0-16-3-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-dotnet-3-pr/s2i-dotnet-3-pr-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-dotnet-3-pr/s2i-dotnet-3-pr-v0-16-3-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-dotnet-3/s2i-dotnet-3-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-dotnet-3/s2i-dotnet-3-v0-16-3-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-go-pr/s2i-go-pr-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-go-pr/s2i-go-pr-v0-16-3-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-go/s2i-go-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-go/s2i-go-v0-16-3-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-java-11-pr/s2i-java-11-pr-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-java-11-pr/s2i-java-11-pr-v0-16-3-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-java-11/s2i-java-11-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-java-11/s2i-java-11-v0-16-3-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-java-8-pr/s2i-java-8-pr-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-java-8-pr/s2i-java-8-pr-v0-16-3-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-java-8/s2i-java-8-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-java-8/s2i-java-8-v0-16-3-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-nodejs-pr/s2i-nodejs-pr-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-nodejs-pr/s2i-nodejs-pr-v0-16-3-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-nodejs/s2i-nodejs-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-nodejs/s2i-nodejs-v0-16-3-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-perl-pr/s2i-perl-pr-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-perl-pr/s2i-perl-pr-v0-16-3-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-perl/s2i-perl-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-perl/s2i-perl-v0-16-3-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-php-pr/s2i-php-pr-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-php-pr/s2i-php-pr-v0-16-3-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-php/s2i-php-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-php/s2i-php-v0-16-3-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-python-3-pr/s2i-python-3-pr-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-python-3-pr/s2i-python-3-pr-v0-16-3-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-python-3/s2i-python-3-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-python-3/s2i-python-3-v0-16-3-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-ruby-pr/s2i-ruby-pr-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-ruby-pr/s2i-ruby-pr-v0-16-3-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-ruby/s2i-ruby-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-ruby/s2i-ruby-v0-16-3-task.yaml
  deploy/resources/addons/02-clustertasks/skopeo-copy/skopeo-copy-task.yaml
  deploy/resources/addons/02-clustertasks/skopeo-copy/skopeo-copy-v0-16-3-task.yaml
Labels: approved, lgtm

#503 Run tekton controller as nonroot
  deploy/resources/pipelines/01-clusterrole.yaml
  deploy/resources/pipelines/02-rolebinding.yaml
Labels: approved, lgtm

#504 Anyuid to every "pipeline" SA
  pkg/controller/rbac/rbac_controller.go
  pkg/flag/flag.go
  test/helpers/helpers.go
  test/testsuites/auto_default_sa.go
Labels: approved, lgtm

#506 Update CLI link for ConsoleCLIDownload
  deploy/resources/addons/04-consolecli/console_cli_download_tkn.yaml
Labels: approved, lgtm
