Repository openshift/tektoncd-pipeline-operator, pull requests merged in 2020-02, with the labels that each got.

#213 Adds cluster tasks
  deploy/resources/v0.9.2/addons/clustertasks/s2i-perl/s2i-perl-task.yaml
  deploy/resources/v0.9.2/addons/clustertasks/s2i-perl/s2i-perl-v0-9-0-task.yaml
  deploy/resources/v0.9.2/addons/clustertasks/s2i-php/s2i-php-task.yaml
  deploy/resources/v0.9.2/addons/clustertasks/s2i-php/s2i-php-v0-9-0-task.yaml
  deploy/resources/v0.9.2/addons/clustertasks/s2i-ruby/s2i-ruby-task.yaml
  deploy/resources/v0.9.2/addons/clustertasks/s2i-ruby/s2i-ruby-v0-9-0-task.yaml
  scripts/update-tasks.sh
Labels: approved, lgtm, ok-to-test, size/L

#219 :robot: Triggering CI on branch 'release-next' after synching to openshift/master
  ci
Labels: kind/sync-fork-to-upstream, size/XS

#224 Add perl pipeline template
  deploy/resources/v0.9.2/addons/pipelines/s2i-perl/s2i-perl-build-deploy.yaml
Labels: approved, lgtm, ok-to-test, size/M

#225 Add ruby pipeline template
  deploy/resources/v0.9.2/addons/pipelines/s2i-ruby/s2i-ruby-build-deploy.yaml
Labels: approved, lgtm, ok-to-test, size/M

#223 Add php pipeline template
  deploy/resources/v0.9.2/addons/pipelines/s2i-php/s2i-php-build-deploy.yaml
Labels: approved, lgtm, ok-to-test, size/M

#222 Add test for conditional manifest transformer
  make/test.mk
  pkg/utils/transform/testdata/with-annotation.yaml
  pkg/utils/transform/testdata/without-annotation.yaml
  pkg/utils/transform/transform_test.go
Labels: approved, lgtm, ok-to-test, size/M

#230 Add mechanism install non-Red-Hat-supported Tasks
  pkg/apis/operator/v1alpha1/config_types.go
  pkg/controller/config/config_controller.go
  pkg/flag/flag.go
  pkg/utils/transform/testdata/test-inject-label-kind-set.yaml
  pkg/utils/transform/testdata/test-inject-label-overwrite.yaml
  pkg/utils/transform/testdata/test-inject-label.yaml
  pkg/utils/transform/testdata/test-replace-kind.yaml
  pkg/utils/transform/transform.go
  pkg/utils/transform/transform_test.go
Labels: approved, lgtm, size/L

#237 Fix java pipeline template for image lookup fails
  deploy/resources/v0.10.1/addons/pipelines/s2i-java-11/s2i-java-11-build-deploy.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#236 Add v0.10.6 CSV
  deploy/olm-catalog/openshift-pipelines-operator/0.10.6/openshift-pipelines-operator.v0.10.6.clusterserviceversion.yaml
  deploy/olm-catalog/openshift-pipelines-operator/0.10.6/operator_v1alpha1_config_crd.yaml
  deploy/olm-catalog/openshift-pipelines-operator/openshift-pipelines-operator.package.yaml
  deploy/operator.yaml
  pkg/flag/flag.go
Labels: approved, lgtm, size/L

#245 Fix all pipeline templates
  deploy/resources/v0.10.1/addons/pipelines/s2i-go/s2i-go-build-deploy.yaml
  deploy/resources/v0.10.1/addons/pipelines/s2i-java-11/s2i-java-11-build-deploy.yaml
  deploy/resources/v0.10.1/addons/pipelines/s2i-nodejs/s2i-nodejs-build-deploy.yaml
  deploy/resources/v0.10.1/addons/pipelines/s2i-perl/s2i-perl-build-deploy.yaml
  deploy/resources/v0.10.1/addons/pipelines/s2i-php/s2i-php-build-deploy.yaml
  deploy/resources/v0.10.1/addons/pipelines/s2i-python/s2i-python-build-deploy.yaml
  deploy/resources/v0.10.1/addons/pipelines/s2i-ruby/s2i-ruby-build-deploy.yaml
Labels: approved, lgtm, ok-to-test, size/S
