Repository openshift/tektoncd-pipeline-operator, pull requests merged in 2020-01, with the labels that each got.

#170 Simplify nightly test payaload fetch mechanism
  openshift/release/fetch-pipeline.sh
  openshift/release/update-to-head.sh
Labels: approved, lgtm, size/M

#173 Keep yamllint rules same across projects
  .yamllint
  deploy/resources/v0.5.2/release.yaml
  deploy/resources/v0.7.0/release.yaml
  deploy/resources/v0.8.0/addons/clustertasks/cluster-role.yaml
  deploy/resources/v0.8.0/pipelines/release.yaml
  deploy/resources/v0.9.2/addons/clustertasks/cluster-role.yaml
Labels: approved, lgtm, size/L

#168 Improve release process
  Makefile
  Release.mk
  docs/release.md
Labels: approved, lgtm, size/L

#177 Add a FAQ Document
  README.md
  docs/faq.md
Labels: approved, lgtm, size/M

#179 Retry fetching the pipeline nightly release
  openshift/release/fetch-pipeline.sh
Labels: approved, lgtm, size/S

#180 Improve Operator Unistall information in FAQ
  docs/faq.md
Labels: approved, lgtm, size/M

#181 Improve Release Doc
  docs/release.md
Labels: approved, lgtm, size/S

#190 :robot: Triggering CI on branch 'release-next' after synching to openshift/master
  ci
Labels: kind/sync-fork-to-upstream, size/XS

#193 Added runafter to sample pipelines
  deploy/resources/v0.9.2/optional/pipelinesamples/docker_build_deploy.yaml
  deploy/resources/v0.9.2/optional/pipelinesamples/s2i_build_deploy.yaml
Labels: approved, lgtm, size/XS

#192 removes v0-8-0 resources from v0-9-2
  deploy/resources/v0.9.2/addons/clustertasks/buildah/buildah-v0-8-0-task.yaml
  deploy/resources/v0.9.2/addons/clustertasks/openshift-client/openshift-client-v0-8-0-task.yaml
  deploy/resources/v0.9.2/addons/clustertasks/s2i-go/s2i-go-v0-8-0-task.yaml
  deploy/resources/v0.9.2/addons/clustertasks/s2i-java-11/s2i-java-11-v0-8-0-task.yaml
  deploy/resources/v0.9.2/addons/clustertasks/s2i-java-8/s2i-java-8-v0-8-0-task.yaml
  deploy/resources/v0.9.2/addons/clustertasks/s2i-nodejs/s2i-nodejs-v0-8-0-task.yaml
  deploy/resources/v0.9.2/addons/clustertasks/s2i-python-3/s2i-python-3-v0-8-0-task.yaml
  deploy/resources/v0.9.2/addons/clustertasks/s2i/s2i-v0-8-0-task.yaml
Labels: approved, lgtm, ok-to-test, size/XL

#202 :robot: Triggering CI on branch 'release-next' after synching to openshift/master
  ci
Labels: kind/sync-fork-to-upstream, size/XS

#187 Add go and java pipeline for +Add flows
  deploy/resources/v0.9.2/addons/pipelines/s2i-go/s2i-go-build-deploy.yaml
  deploy/resources/v0.9.2/addons/pipelines/s2i-java-11/s2i-java-11-build-deploy.yaml
  pkg/controller/config/config_controller.go
  pkg/flag/flag.go
  pkg/utils/transform/transform.go
Labels: approved, lgtm, ok-to-test, size/L

#205 Add nodejs pipeline template
  deploy/resources/v0.9.2/addons/pipelines/s2i-nodejs/s2i-nodejs-build-deploy.yaml
Labels: approved, bugzilla/valid-bug, lgtm, ok-to-test, size/M

#206 Add python-3 pipeline template
  deploy/resources/v0.9.2/addons/pipelines/s2i-python/s2i-python-build-deploy.yaml
Labels: approved, bugzilla/valid-bug, lgtm, ok-to-test, size/M

#210 Adds runAfter to pipeline templates
  deploy/resources/v0.9.2/addons/pipelines/s2i-go/s2i-go-build-deploy.yaml
  deploy/resources/v0.9.2/addons/pipelines/s2i-java-11/s2i-java-11-build-deploy.yaml
Labels: approved, bugzilla/valid-bug, lgtm, ok-to-test, size/XS

#211 Adds buildah pipeline template
  deploy/resources/v0.9.2/addons/pipelines/buildah/buildah-build-deploy.yaml
Labels: approved, lgtm, ok-to-test, size/M
