Repository openshift/tektoncd-pipeline-operator, pull requests merged in 2020-03, with the labels that each got.

#252 Add 0.10.7 csv to master
  deploy/olm-catalog/openshift-pipelines-operator/0.10.7/openshift-pipelines-operator.v0.10.7.clusterserviceversion.yaml
  deploy/olm-catalog/openshift-pipelines-operator/0.10.7/operator_v1alpha1_config_crd.yaml
  deploy/olm-catalog/openshift-pipelines-operator/openshift-pipelines-operator.package.yaml
  deploy/operator.yaml
  deploy/resources/v0.10.1/addons/pipelines/buildah/buildah-build-deploy.yaml
Labels: approved, lgtm, size/XL

#257 :robot: Triggering CI on branch 'release-next' after synching to openshift/master
  ci
Labels: kind/sync-fork-to-upstream, size/XS

#259 :robot: Triggering CI on branch 'release-next' after synching to openshift/master
  ci
Labels: kind/sync-fork-to-upstream, size/XS

#261 :robot: Triggering CI on branch 'release-next' after synching to openshift/master
  ci
Labels: kind/sync-fork-to-upstream, size/XS

#265 Changes pipelines image prefix env var and minor code refactor
  README.md
  pkg/controller/config/config_controller.go
  pkg/controller/config/config_controller_test.go
  pkg/utils/transform/transform.go
  pkg/utils/transform/transform_test.go
Labels: approved, lgtm, size/M

#264 Update Triggers to v0.3.1
  deploy/resources/devel/addons/triggers/tektoncd-triggers-v0.3.1.yaml
Labels: approved, lgtm, size/M

#266 Use Tag based url to fetch pipeline payload
  openshift/release/fetch-pipeline.sh
Labels: approved, lgtm

#268 Fix webhook validation
  deploy/resources/devel/addons/clustertasks/buildah/buildah-task.yaml
  deploy/resources/devel/addons/clustertasks/buildah/buildah-v0-11-0-rc2-task.yaml
  deploy/resources/devel/addons/clustertasks/cluster-role.yaml
  deploy/resources/devel/addons/clustertasks/cluster-rolebinding.yaml
  deploy/resources/devel/addons/clustertasks/openshift-client/openshift-client-task.yaml
  deploy/resources/devel/addons/clustertasks/openshift-client/openshift-client-v0-11-0-rc2-task.yaml
  deploy/resources/devel/addons/clustertasks/s2i-go/s2i-go-task.yaml
  deploy/resources/devel/addons/clustertasks/s2i-go/s2i-go-v0-11-0-rc2-task.yaml
  deploy/resources/devel/addons/clustertasks/s2i-java-11/s2i-java-11-task.yaml
  deploy/resources/devel/addons/clustertasks/s2i-java-11/s2i-java-11-v0-11-0-rc2-task.yaml
  deploy/resources/devel/addons/clustertasks/s2i-java-8/s2i-java-8-task.yaml
  deploy/resources/devel/addons/clustertasks/s2i-java-8/s2i-java-8-v0-11-0-rc2-task.yaml
  deploy/resources/devel/addons/clustertasks/s2i-nodejs/s2i-nodejs-task.yaml
  deploy/resources/devel/addons/clustertasks/s2i-nodejs/s2i-nodejs-v0-11-0-rc2-task.yaml
  deploy/resources/devel/addons/clustertasks/s2i-perl/s2i-perl-task.yaml
  deploy/resources/devel/addons/clustertasks/s2i-perl/s2i-perl-v0-11-0-rc2-task.yaml
  deploy/resources/devel/addons/clustertasks/s2i-php/s2i-php-task.yaml
  deploy/resources/devel/addons/clustertasks/s2i-php/s2i-php-v0-11-0-rc2-task.yaml
  deploy/resources/devel/addons/clustertasks/s2i-python-3/s2i-python-3-task.yaml
  deploy/resources/devel/addons/clustertasks/s2i-python-3/s2i-python-3-v0-11-0-rc2-task.yaml
  deploy/resources/devel/addons/clustertasks/s2i-ruby/s2i-ruby-task.yaml
  deploy/resources/devel/addons/clustertasks/s2i-ruby/s2i-ruby-v0-11-0-rc2-task.yaml
  deploy/resources/devel/addons/clustertasks/s2i/s2i-task.yaml
  deploy/resources/devel/addons/clustertasks/s2i/s2i-v0-11-0-rc2-task.yaml
  deploy/resources/devel/addons/pipelines/buildah/buildah-build-deploy.yaml
  deploy/resources/devel/addons/pipelines/s2i-go/s2i-go-build-deploy.yaml
  deploy/resources/devel/addons/pipelines/s2i-java-11/s2i-java-11-build-deploy.yaml
  deploy/resources/devel/addons/pipelines/s2i-nodejs/s2i-nodejs-build-deploy.yaml
  deploy/resources/devel/addons/pipelines/s2i-perl/s2i-perl-build-deploy.yaml
  deploy/resources/devel/addons/pipelines/s2i-php/s2i-php-build-deploy.yaml
  deploy/resources/devel/addons/pipelines/s2i-python/s2i-python-build-deploy.yaml
  deploy/resources/devel/addons/pipelines/s2i-ruby/s2i-ruby-build-deploy.yaml
  deploy/resources/devel/optional/pipelinesamples/docker_build_deploy.yaml
  deploy/resources/devel/optional/pipelinesamples/s2i_build_deploy.yaml
  deploy/resources/devel/optional/pipelinesamples/simple_pipeline.yaml
  deploy/resources/devel/optional/tasksnippets/buildah-task-snippet.yaml
  deploy/resources/devel/optional/tasksnippets/openshift-client-task-snippet.yaml
  deploy/resources/devel/optional/tasksnippets/s2i-go-task-snippet.yaml
  deploy/resources/devel/optional/tasksnippets/s2i-java-11-task-snippet.yaml
  deploy/resources/devel/optional/tasksnippets/s2i-java-8-task-snippet.yaml
  deploy/resources/devel/optional/tasksnippets/s2i-nodejs-task-snippet.yaml
  deploy/resources/devel/optional/tasksnippets/s2i-python-3-task-snippet.yaml
  deploy/resources/devel/optional/tasksnippets/s2i-task-snippet.yaml
  deploy/resources/devel/pipelines/release.yaml
  deploy/role.yaml
  pkg/flag/flag.go
Labels: approved, lgtm

#267 :robot: Triggering CI on branch 'release-next' after synching to openshift/master
  ci
Labels: approved, kind/sync-fork-to-upstream
