Repository openshift/tektoncd-pipeline-operator, pull requests merged in 2020-12, with the labels that each got.

#536 :robot: Triggering CI on branch 'release-next' after synching to openshift/master
  ci
Labels: approved, kind/sync-fork-to-upstream, lgtm

#539 Change to manifest list sha for multiarch support
  deploy/resources/addons/02-clustertasks/s2i-dotnet-3-pr/s2i-dotnet-3-pr-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-dotnet-3-pr/s2i-dotnet-3-pr-v0-16-3-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-dotnet-3/s2i-dotnet-3-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-dotnet-3/s2i-dotnet-3-v0-16-3-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-go-pr/s2i-go-pr-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-go-pr/s2i-go-pr-v0-16-3-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-go/s2i-go-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-go/s2i-go-v0-16-3-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-java-11-pr/s2i-java-11-pr-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-java-11-pr/s2i-java-11-pr-v0-16-3-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-java-11/s2i-java-11-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-java-11/s2i-java-11-v0-16-3-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-java-8-pr/s2i-java-8-pr-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-java-8-pr/s2i-java-8-pr-v0-16-3-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-java-8/s2i-java-8-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-java-8/s2i-java-8-v0-16-3-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-nodejs-pr/s2i-nodejs-pr-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-nodejs-pr/s2i-nodejs-pr-v0-16-3-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-nodejs/s2i-nodejs-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-nodejs/s2i-nodejs-v0-16-3-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-perl-pr/s2i-perl-pr-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-perl-pr/s2i-perl-pr-v0-16-3-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-perl/s2i-perl-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-perl/s2i-perl-v0-16-3-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-php-pr/s2i-php-pr-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-php-pr/s2i-php-pr-v0-16-3-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-php/s2i-php-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-php/s2i-php-v0-16-3-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-python-3-pr/s2i-python-3-pr-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-python-3-pr/s2i-python-3-pr-v0-16-3-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-python-3/s2i-python-3-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-python-3/s2i-python-3-v0-16-3-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-ruby-pr/s2i-ruby-pr-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-ruby-pr/s2i-ruby-pr-v0-16-3-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-ruby/s2i-ruby-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-ruby/s2i-ruby-v0-16-3-task.yaml
  scripts/update-tasks.sh
Labels: approved, lgtm

#544 Remove enable repo in Dockerfile
  openshift-ci/Dockerfile.tools
Labels: approved, lgtm

#543 :robot: Triggering CI on branch 'release-next' after synching to openshift/master
  ci
Labels: approved, kind/sync-fork-to-upstream, lgtm

#542 adds default value for version
  pkg/controller/config/config_controller.go
  pkg/flag/flag.go
  pkg/utils/addons/addons.go
  pkg/utils/addons/testdata/s2i-dotnet-3-deployment-pr.golden
  pkg/utils/addons/testdata/s2i-dotnet-3-deployment.golden
  pkg/utils/addons/testdata/s2i-dotnet-3-knative-pr.golden
  pkg/utils/addons/testdata/s2i-dotnet-3-knative.golden
  pkg/utils/addons/testdata/s2i-dotnet-3-pr.golden
  pkg/utils/addons/testdata/s2i-dotnet-3.golden
  pkg/utils/addons/testdata/s2i-nodejs-deployment-pr.golden
  pkg/utils/addons/testdata/s2i-nodejs-deployment.golden
  pkg/utils/addons/testdata/s2i-nodejs-knative-pr.golden
  pkg/utils/addons/testdata/s2i-nodejs-knative.golden
  pkg/utils/addons/testdata/s2i-nodejs-pr.golden
  pkg/utils/addons/testdata/s2i-nodejs.golden
  pkg/utils/addons/testdata/s2i-perl-deployment-pr.golden
  pkg/utils/addons/testdata/s2i-perl-deployment.golden
  pkg/utils/addons/testdata/s2i-perl-knative-pr.golden
  pkg/utils/addons/testdata/s2i-perl-knative.golden
  pkg/utils/addons/testdata/s2i-perl-pr.golden
  pkg/utils/addons/testdata/s2i-perl.golden
  pkg/utils/addons/testdata/s2i-php-deployment-pr.golden
  pkg/utils/addons/testdata/s2i-php-deployment.golden
  pkg/utils/addons/testdata/s2i-php-knative-pr.golden
  pkg/utils/addons/testdata/s2i-php-knative.golden
  pkg/utils/addons/testdata/s2i-php-pr.golden
  pkg/utils/addons/testdata/s2i-php.golden
  pkg/utils/addons/testdata/s2i-python-3-deployment-pr.golden
  pkg/utils/addons/testdata/s2i-python-3-deployment.golden
  pkg/utils/addons/testdata/s2i-python-3-knative-pr.golden
  pkg/utils/addons/testdata/s2i-python-3-knative.golden
  pkg/utils/addons/testdata/s2i-python-3-pr.golden
  pkg/utils/addons/testdata/s2i-python-3.golden
  pkg/utils/addons/testdata/s2i-ruby-deployment-pr.golden
  pkg/utils/addons/testdata/s2i-ruby-deployment.golden
  pkg/utils/addons/testdata/s2i-ruby-knative-pr.golden
  pkg/utils/addons/testdata/s2i-ruby-knative.golden
  pkg/utils/addons/testdata/s2i-ruby-pr.golden
  pkg/utils/addons/testdata/s2i-ruby.golden
Labels: approved, lgtm

#547 adds default value for version
  pkg/controller/config/config_controller.go
  pkg/flag/flag.go
  pkg/utils/addons/addons.go
  pkg/utils/addons/testdata/s2i-dotnet-3-deployment-pr.golden
  pkg/utils/addons/testdata/s2i-dotnet-3-deployment.golden
  pkg/utils/addons/testdata/s2i-dotnet-3-knative-pr.golden
  pkg/utils/addons/testdata/s2i-dotnet-3-knative.golden
  pkg/utils/addons/testdata/s2i-dotnet-3-pr.golden
  pkg/utils/addons/testdata/s2i-dotnet-3.golden
  pkg/utils/addons/testdata/s2i-nodejs-deployment-pr.golden
  pkg/utils/addons/testdata/s2i-nodejs-deployment.golden
  pkg/utils/addons/testdata/s2i-nodejs-knative-pr.golden
  pkg/utils/addons/testdata/s2i-nodejs-knative.golden
  pkg/utils/addons/testdata/s2i-nodejs-pr.golden
  pkg/utils/addons/testdata/s2i-nodejs.golden
  pkg/utils/addons/testdata/s2i-perl-deployment-pr.golden
  pkg/utils/addons/testdata/s2i-perl-deployment.golden
  pkg/utils/addons/testdata/s2i-perl-knative-pr.golden
  pkg/utils/addons/testdata/s2i-perl-knative.golden
  pkg/utils/addons/testdata/s2i-perl-pr.golden
  pkg/utils/addons/testdata/s2i-perl.golden
  pkg/utils/addons/testdata/s2i-php-deployment-pr.golden
  pkg/utils/addons/testdata/s2i-php-deployment.golden
  pkg/utils/addons/testdata/s2i-php-knative-pr.golden
  pkg/utils/addons/testdata/s2i-php-knative.golden
  pkg/utils/addons/testdata/s2i-php-pr.golden
  pkg/utils/addons/testdata/s2i-php.golden
  pkg/utils/addons/testdata/s2i-python-3-deployment-pr.golden
  pkg/utils/addons/testdata/s2i-python-3-deployment.golden
  pkg/utils/addons/testdata/s2i-python-3-knative-pr.golden
  pkg/utils/addons/testdata/s2i-python-3-knative.golden
  pkg/utils/addons/testdata/s2i-python-3-pr.golden
  pkg/utils/addons/testdata/s2i-python-3.golden
  pkg/utils/addons/testdata/s2i-ruby-deployment-pr.golden
  pkg/utils/addons/testdata/s2i-ruby-deployment.golden
  pkg/utils/addons/testdata/s2i-ruby-knative-pr.golden
  pkg/utils/addons/testdata/s2i-ruby-knative.golden
  pkg/utils/addons/testdata/s2i-ruby-pr.golden
  pkg/utils/addons/testdata/s2i-ruby.golden
Labels: approved, lgtm

#549 Skip upstream tasks when arch is P and Z, fix to branch v1.2.x
  pkg/controller/config/config_controller.go
Labels: approved, lgtm, needs-ok-to-test

#507 Connect the tests to the main test
  test/testgroups/cluster_crd.go
  test/testsuites/auto_default_sa.go
Labels: approved, lgtm

#546 Skip installation of upstream tasks for ppc64le and s390x
  pkg/controller/config/config_controller.go
Labels: approved, lgtm, needs-ok-to-test

#556 :robot: Triggering CI on branch 'release-next' after synching to openshift/master
  ci
Labels: kind/sync-fork-to-upstream
