Repository openshift/tektoncd-pipeline-operator, pull requests merged in 2020-07, with the labels that each got.

#344 :robot: Triggering CI on branch 'release-next' after synching to openshift/master
  ci
Labels: kind/sync-fork-to-upstream

#345 Fixed ODC-4234
  deploy/resources/devel/addons/02-clustertriggerbindings/github.yaml
Labels: approved, lgtm, ok-to-test

#350 :robot: Triggering CI on branch 'release-next' after synching to openshift/master
  ci
Labels: kind/sync-fork-to-upstream, lgtm

#353 Change Buildah and S2I Image to Productized
  scripts/update-tasks.sh
Labels: approved, lgtm

#360 Fix script to fetch version
  openshift/release/fetch-pipeline.sh
Labels: approved, lgtm

#362 Test add some debug to see why the CI URL fetch is failing
  openshift/release/fetch-pipeline.sh
Labels: approved, lgtm

#363 fetch-versions: Cleanups the testing logics and make it more robust
  openshift/release/fetch-pipeline.sh
Labels: approved, lgtm

#365 CommunityResourceURLs: update according to catalog organization…
  pkg/flag/flag.go
Labels: approved, lgtm

#367 Add debug to debug tomrrow job
  openshift/release/fetch-pipeline.sh
Labels: approved, lgtm

#371 Bump tektoncd/triggers to v0.6.1
  deploy/resources/devel/addons/01-triggers/tektoncd-triggers-v0.6.1.yaml
  deploy/resources/devel/addons/01-triggers/triggers-4.0-aggregate-roles-fix.yaml
Labels: approved, lgtm

#372 Bump pipeline to v0.14.2
  deploy/resources/devel/pipelines/00-release.yaml
Labels: approved, lgtm

#377 Bump pipeline to v0.14.3
  deploy/resources/devel/pipelines/00-release.yaml
Labels: approved, lgtm

#374 Add pipeline and trigger version
  deploy/crds/operator_v1alpha1_config_crd.yaml
  pkg/apis/operator/v1alpha1/config_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/operator/v1alpha1/zz_generated.openapi.go
  pkg/controller/config/config_controller.go
Labels: approved, lgtm

#379 Remove debug statement from fetch-pipelines script 🧹
  openshift/release/fetch-pipeline.sh
Labels: approved, lgtm
