Repository openshift/tektoncd-pipeline-operator, pull requests merged in 2020-05, with the labels that each got.

#305 Fix lint CI
  make/lint.mk
Labels: approved, lgtm

#311 Devel 2 0.4.0
  deploy/resources/v0.11.3/addons/01-triggers/tektoncd-triggers-v0.4.0.yaml
Labels: approved, lgtm

#313 Refactoring regarding clusterTasks
  deploy/resources/v0.11.3/addons/03-clustertasks/buildah/buildah-task.yaml
  deploy/resources/v0.11.3/addons/03-clustertasks/buildah/buildah-v0-11-3-task.yaml
  deploy/resources/v0.11.3/addons/03-clustertasks/openshift-client/openshift-client-task.yaml
  deploy/resources/v0.11.3/addons/03-clustertasks/openshift-client/openshift-client-v0-11-3-task.yaml
  deploy/resources/v0.11.3/addons/03-clustertasks/s2i-dotnet-3/s2i-dotnet-3-task.yaml
  deploy/resources/v0.11.3/addons/03-clustertasks/s2i-dotnet-3/s2i-dotnet-3-v0-11-3-task.yaml
  deploy/resources/v0.11.3/addons/03-clustertasks/s2i-go/s2i-go-task.yaml
  deploy/resources/v0.11.3/addons/03-clustertasks/s2i-go/s2i-go-v0-11-3-task.yaml
  deploy/resources/v0.11.3/addons/03-clustertasks/s2i-java-11/s2i-java-11-task.yaml
  deploy/resources/v0.11.3/addons/03-clustertasks/s2i-java-11/s2i-java-11-v0-11-3-task.yaml
  deploy/resources/v0.11.3/addons/03-clustertasks/s2i-java-8/s2i-java-8-task.yaml
  deploy/resources/v0.11.3/addons/03-clustertasks/s2i-java-8/s2i-java-8-v0-11-3-task.yaml
  deploy/resources/v0.11.3/addons/03-clustertasks/s2i-nodejs/s2i-nodejs-task.yaml
  deploy/resources/v0.11.3/addons/03-clustertasks/s2i-nodejs/s2i-nodejs-v0-11-3-task.yaml
  deploy/resources/v0.11.3/addons/03-clustertasks/s2i-perl/s2i-perl-task.yaml
  deploy/resources/v0.11.3/addons/03-clustertasks/s2i-perl/s2i-perl-v0-11-3-task.yaml
  deploy/resources/v0.11.3/addons/03-clustertasks/s2i-php/s2i-php-task.yaml
  deploy/resources/v0.11.3/addons/03-clustertasks/s2i-php/s2i-php-v0-11-3-task.yaml
  deploy/resources/v0.11.3/addons/03-clustertasks/s2i-python-3/s2i-python-3-task.yaml
  deploy/resources/v0.11.3/addons/03-clustertasks/s2i-python-3/s2i-python-3-v0-11-3-task.yaml
  deploy/resources/v0.11.3/addons/03-clustertasks/s2i-ruby/s2i-ruby-task.yaml
  deploy/resources/v0.11.3/addons/03-clustertasks/s2i-ruby/s2i-ruby-v0-11-3-task.yaml
  deploy/resources/v0.11.3/addons/03-clustertasks/s2i/s2i-task.yaml
  deploy/resources/v0.11.3/addons/03-clustertasks/s2i/s2i-v0-11-3-task.yaml
  pkg/controller/config/config_controller.go
  pkg/flag/flag.go
Labels: approved, lgtm

#316 Add pipeline templates for knative
  deploy/resources/v0.11.3/addons/04-pipelines/knative/buildah/buildah-build-deploy.yaml
  deploy/resources/v0.11.3/addons/04-pipelines/knative/s2i-dotnet-3/s2i-dotnet-3-build-deploy.yaml
  deploy/resources/v0.11.3/addons/04-pipelines/knative/s2i-go/s2i-go-build-deploy.yaml
  deploy/resources/v0.11.3/addons/04-pipelines/knative/s2i-java-11/s2i-java-11-build-deploy.yaml
  deploy/resources/v0.11.3/addons/04-pipelines/knative/s2i-nodejs/s2i-nodejs-build-deploy.yaml
  deploy/resources/v0.11.3/addons/04-pipelines/knative/s2i-perl/s2i-perl-build-deploy.yaml
  deploy/resources/v0.11.3/addons/04-pipelines/knative/s2i-php/s2i-php-build-deploy.yaml
  deploy/resources/v0.11.3/addons/04-pipelines/knative/s2i-python/s2i-python-build-deploy.yaml
  deploy/resources/v0.11.3/addons/04-pipelines/knative/s2i-ruby/s2i-ruby-build-deploy.yaml
Labels: approved, lgtm

#319 :robot: Triggering CI on branch 'release-next' after synching to openshift/master
  ci
Labels: kind/sync-fork-to-upstream

#321 Fix lint CI
  make/lint.mk
Labels: approved, lgtm

#323 Fix fetch pipeline logic
  openshift/release/fetch-pipeline.sh
Labels: approved, lgtm

#308 Update non redhat resources to use image value from env
  deploy/operator.yaml
  pkg/controller/config/config_controller.go
  scripts/update-tasks.sh
Labels: approved, lgtm

#296 Fix typos
  README.md
  docs/release.md
  make/lint.mk
  pkg/controller/config/config_controller.go
  pkg/utils/transform/transform.go
Labels: approved, lgtm, ok-to-test

#325 Fix e2e
  test/helpers/helpers.go
  test/testsuites/auto_install_pipeline.go
Labels: approved, lgtm
