Repository openshift/tektoncd-pipeline-operator, pull requests merged in 2020-09, with the labels that each got.

#429 :robot: Triggering CI on branch 'release-next' after synching to openshift/master
  ci
Labels: kind/sync-fork-to-upstream

#450 Update operator_v1alpha1_config_crd.yaml: Remove required 'pipelineVersion' and 'triggersVersion' fields
  bundle/manifests/operator_v1alpha1_config_crd.yaml
Labels: approved, lgtm, ok-to-test

#451 Small additions to prerequisites in README.md
  README.md
Labels: approved, lgtm, ok-to-test

#460 Add role and rolebinding for openshift-pipelines namespace
  deploy/resources/addons/03-pipelines/role.yaml
  deploy/resources/addons/03-pipelines/rolebinding.yaml
Labels: approved, lgtm

#464 Update clustertask, pipelines and triggers for v1.2
  deploy/resources/addons/02-clustertasks/buildah-pr/buildah-pr-task.yaml
  deploy/resources/addons/02-clustertasks/buildah-pr/buildah-pr-v0-16-3-task.yaml
  deploy/resources/addons/02-clustertasks/buildah/buildah-task.yaml
  deploy/resources/addons/02-clustertasks/buildah/buildah-v0-16-3-task.yaml
  deploy/resources/addons/02-clustertasks/git-clone/git-clone-task.yaml
  deploy/resources/addons/02-clustertasks/git-clone/git-clone-v0-16-3-task.yaml
  deploy/resources/addons/02-clustertasks/openshift-client/openshift-client-task.yaml
  deploy/resources/addons/02-clustertasks/openshift-client/openshift-client-v0-16-3-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-dotnet-3-pr/s2i-dotnet-3-pr-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-dotnet-3-pr/s2i-dotnet-3-pr-v0-16-3-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-dotnet-3/s2i-dotnet-3-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-dotnet-3/s2i-dotnet-3-v0-16-3-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-go-pr/s2i-go-pr-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-go-pr/s2i-go-pr-v0-16-3-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-go/s2i-go-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-go/s2i-go-v0-16-3-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-java-11-pr/s2i-java-11-pr-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-java-11-pr/s2i-java-11-pr-v0-16-3-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-java-11/s2i-java-11-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-java-11/s2i-java-11-v0-16-3-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-java-8-pr/s2i-java-8-pr-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-java-8-pr/s2i-java-8-pr-v0-16-3-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-java-8/s2i-java-8-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-java-8/s2i-java-8-v0-16-3-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-nodejs-pr/s2i-nodejs-pr-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-nodejs-pr/s2i-nodejs-pr-v0-16-3-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-nodejs/s2i-nodejs-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-nodejs/s2i-nodejs-v0-16-3-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-perl-pr/s2i-perl-pr-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-perl-pr/s2i-perl-pr-v0-16-3-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-perl/s2i-perl-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-perl/s2i-perl-v0-16-3-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-php-pr/s2i-php-pr-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-php-pr/s2i-php-pr-v0-16-3-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-php/s2i-php-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-php/s2i-php-v0-16-3-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-python-3-pr/s2i-python-3-pr-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-python-3-pr/s2i-python-3-pr-v0-16-3-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-python-3/s2i-python-3-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-python-3/s2i-python-3-v0-16-3-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-ruby-pr/s2i-ruby-pr-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-ruby-pr/s2i-ruby-pr-v0-16-3-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-ruby/s2i-ruby-task.yaml
  deploy/resources/addons/02-clustertasks/s2i-ruby/s2i-ruby-v0-16-3-task.yaml
  deploy/resources/optional/tasksnippets/buildah-pr-task-snippet.yaml
  deploy/resources/optional/tasksnippets/buildah-task-snippet.yaml
  deploy/resources/pipelines/00-release.yaml
  deploy/resources/triggers/tektoncd-triggers-v0.8.1.yaml
  scripts/update-tasks.sh
Labels: approved, lgtm

#466 adds community tasks
  deploy/operator.yaml
  pkg/flag/flag.go
Labels: approved, lgtm

#467 Refactor in clustertask provided type
  bundle/manifests/openshift-pipelines-operator.clusterserviceversion.yaml
  deploy/operator.yaml
  deploy/resources/addons/02-clustertasks/kn/kn-task.yaml
  deploy/resources/addons/02-clustertasks/kn/kn-v0-16-3-task.yaml
  pkg/controller/config/config_controller.go
  pkg/flag/flag.go
  scripts/update-tasks.sh
Labels: approved, lgtm
